version = 0.1
[default.deploy.parameters]
stack_name = "mcp-chat"
resolve_s3 = true
s3_prefix = "mcp-chat"
region = "us-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
