AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: FastAPI on Lambda

Resources:
  FastApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: main.handler
      Runtime: python3.11
      Timeout: 30
      MemorySize: 512
      Environment:
        Variables:
          OPENAI_API_KEY: your-key
          SUPABASE_DB_NAME: your-db
          SUPABASE_DB_USER: your-user
          SUPABASE_DB_PASSWORD: your-password
          SUPABASE_DB_HOST: your-host
          SUPABASE_DB_PORT: your-port
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
